# This is a basic workflow to help you get started with Actions

name: Build Packages

# Controls when the action will run. 
on:
  push:
    branches: [ main, dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-binary:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - name: Display Go version
        run: go version

      - name: Go build
        run:
          go build

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: spuddns-binary
          path: spuddns

  build-deb:

    runs-on: ubuntu-latest

    needs: build-binary

    steps:

      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt install -y build-essential debhelper dh-golang

      - name: Download binary
        uses: actions/download-artifact@v4
        with:
          name: spuddns-binary

      - name: Build debian
        run: |
          mkdir -p build
          cp spuddns build/spuddns
          dpkg-buildpackage
          pwd
          ls -l ..

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: spuddns-debian-package
          path: /home/runner/work/spuddns/*amd64*
