# This is a basic workflow to help you get started with Actions

name: Build Packages

# Controls when the action will run. 
on:
  push:
    branches: [ main, dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-debian:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - name: Display Go version
        run: go version

      - name: Install dependencies
        run: sudo apt install -y build-essential debhelper dh-golang

      - name: Build debian
        run: |
          mkdir -p github.com/thenaterhood/spuddns
          cp -r !(github.com) github.com/thenaterhood/spuddns/
          dpkg-buildpackage

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: spuddns-debian-package
          path: "*.deb"
